server:
  port: 8080

spring:
  #Redis配置
  redis:
    # redis单机配置
    database: 1
    host: 127.0.0.1
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数(使用负值表示没有限制) 默认8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 #连接池中的最小空闲连接
        max-idle: 20 #连接池中的最大空闲连接

message:
   url: http://10.108.71.14:8081